export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
//export const LOGIN_TO_ACCOUNT = 'LOGIN_TO_ACCOUNT';